name: transit_tracker
description: Cross-platform transit tracker for anonymous location aggregation and visualization.
publish_to: "none"

version: 0.1.0
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  flutter_cache_manager: ^3.4.1
  latlong2: ^0.9.0
  http: ^1.4.0
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6
  test: ^1.25.15
  file: ^7.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
