name: transit_tracker
description: Cross-platform transit tracker for anonymous location aggregation and visualization.
publish_to: "none"

version: 0.1.0
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^8.1.1
  flutter_cache_manager: ^3.4.1
  latlong2: ^0.9.0
  http: ^1.4.0
  url_launcher: ^6.3.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  dropdown_button2: ^2.3.9

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.6
  test: ^1.25.15
  file: ^7.0.1
  flutter_flavorizr: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env.dev
    - assets/env/.env.prod
    - assets/config/zones.json
    - assets/tiles/16/
    - assets/lang/
    - test/assets/tiles/16/1337_420.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flavorizr:
  app:
    android:
      flavorDimensions: "environment"
    ios:
      skip: true # TBD
  flavors:
    dev:
      app:
        name: "TransitTracker Dev"
      android:
        applicationId: "com.transittracker.app.dev"
      ios:
        bundleId: "com.transittracker.app.dev"
      env:
        BASE_TILE_URL: http://10.0.2.2:3000/tiles
    prod:
      app:
        name: "TransitTracker"
      android:
        applicationId: "com.transittracker.app"
      ios:
        bundleId: "com.transittracker.app"
      env:
        BASE_TILE_URL: https://prod-link.here/tiles
